language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: igzquPumbAbDsb9nM2XEZIGfKKKa1tNcxyUoSvcVQGtWgc1GHgaFF4aR21EbtlKwNNoix25TPKe9KOjhSS5ezTIa07NamyouYP6AT5uAtAVBdH+B716lp4WSaNTVrsEtrZFTVNQ5UIIGJm2rt9RrZKR5O0zETjnNaHPU+DXKUa4gAdrz31kHoaTAEcUI54Kd6DLS8Jjkn9uc0kDPmnAWabYwZR6RP8IR7Smx6CzkHneClBy5oAiRiy631vjv5HyIRxnX9o7jLKVjyRnGrh5vJnTL+vSgBhOpzIKGmYU0VzcMis0Oexq4wiGJuML+yJDsBqogoZLW8ECxC56ZyAVpSn66MdkNPjicMvAYWMXwYUPB9EGFHEZYCU7zOKawyeGuCjzM9nMFvr6wrnc7ClytcklsLb2NVIRaoxgwsaFhaFlUBB0P233DAKVgecmxxXf3FSKVdZtQRngGGqe1aDjc0lYVY8Uw7oLnmUTDarAYMVVqMPak+N2yfwi1fd0LLMkxoNIoB81RKNs7AV+WCEy9PFFaX9Ssc5H2LmQSiaM1M5Y8a+NkttUKep4ndHK4EWGfDk7rQmSTPpP1ZmI/2XTpwXeCp+7k9JjAtCaZhYuFDDc9s3eWHpo6+rRz/GIn60ud3EiFIniypPLOTpch3mEixw70JQ/NQKgEQvZ0DAyvKmo=
  app: lit-tundra-76700
  on:
    repo: RyanOkamuro/wine_select
